[Grupo 14] Adiciona requisito 11
tryber/sd-011-project-frontend-online-store pull request #394
Opened 2021-06-17 19:45 UTC by heyset

2021-06-17 21:46 UTC, renanvamo approved these changes

2021-06-17 21:51 UTC, RafaelCes commented on src/pages/Product.jsx
> +      const userEvaluation = { ...evaluationForm, id: evaluationForm.id };
```suggestion
      const userEvaluation = { ...evaluationForm, id: evaluationForm.email };
```

como a gente discutiu sobre no discord

2021-06-17 21:53 UTC, RafaelCes requested changes
só aquela mudnaça que a gente discutiu Inacio.

2021-06-17 21:55 UTC, RafaelCes approved these changes
apreovado!

2021-06-18 19:52 UTC, jorgeramires approved these changes

2021-06-18 20:23 UTC, merged