[Equipe 26] Requisito 11
tryber/sd-011-project-frontend-online-store pull request #546
Opened 2021-06-18 22:31 UTC by Gribeir0

2021-06-18 22:46 UTC, Luiz-Wendel requested changes
Boa Gabriel! 🚀

2021-06-18 22:46 UTC, Luiz-Wendel commented on src/components/CustomerRating.js
> +          <p>Intens com * são obrigatórios</p>
```suggestion
          <p>Itens com * são obrigatórios</p>
```

2021-06-18 22:50 UTC, Luiz-Wendel approved these changes

2021-06-18 23:03 UTC, talescoelho reviewed
:thinking:

2021-06-18 23:03 UTC, talescoelho commented on src/pages/ProductDetails.js
> +      console.log(productRatings);
```suggestion
```
:thinking:

2021-06-18 23:04 UTC, talescoelho approved these changes

2021-06-24 16:22 UTC, Luiz-Wendel approved these changes

2021-06-25 11:48 UTC, talescoelho approved these changes
Ficou mto bom!!

2021-06-29 22:20 UTC, merged